---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control


backendservers:
    hosts:
      gcloud-backend-server:
        ansible_host: devops-gcloud
      azure-backend-server:
        ansible_host: devops-backend-azure
      azure-docker-server:
        ansible_host: devops-azure  

frontendservers:
    hosts:
      azure-backend-server:
        ansible_host: devops-backend-azure

dbservers:
    hosts:
      azure-db-server:
          ansible_host: devops-db-azure