---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

backendservers:
    hosts:
      gcloud-backend-server:
        ansible_host: devops-gcloud
      azure-backend-server:
        ansible_host: devops-backend-azure

frontendservers:
    hosts:
      azure-frontend-server:
        ansible_host: devops-azure

dbservers:
    hosts:
      dbserver-vm:
          ansible_host: dbserver
      azure-db-server:
          ansible_host: devops-db-azure