---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

appservers:
    hosts:
      gcloud-app-server:
        ansible_host: devops-gcloud

webservers:
    hosts:
      azure-web-server:
        ansible_host: devops-azure