---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

appservers:
    hosts:
      gcloud-app-server:
        ansible_host: devops-gcloud

webservers:
    hosts:
      azure-web-server:
        ansible_host: devops-azure

dbservers:
    hosts:
      dbserver-vm:
          ansible_host: dbserver
      azure-db-server:
          ansible_host: devops-db-azure