backapp:
  env:
    server.port: "{{backapp_port}}"
    spring.datasource.username: dbuser
    spring.datasource.password: pass123
    spring.datasource.url: jdbc:postgresql://20.166.249.54:5432/BloodDonors
    frontend.ip: http://20.199.11.65

frontapp:
  env:
    VITE_BACKEND: http://20.199.11.65:9090

service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar target/BloodDonorApp-0.0.1-SNAPSHOT.jar"