app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: dbuser
    spring.datasource.password: pass123
    spring.datasource.url: jdbc:postgresql://20.166.249.54:5432/BloodDonors
    frontend.ip: http://20.199.11.65
    


service:
  workingdir: "/home/rc/spring"
  execstart: "java -jar target/BloodDonorApp-0.0.1-SNAPSHOT.jar"
