---
- hosts: backendservers

  pre_tasks:
    - name: Install Java
      apt:
          name: openjdk-21-jdk
          state: present
          update_cache: yes
      become: yes

  tasks:
      - name: "debug appdir"
        ansible.builtin.debug:
          msg: "appdir {{ansible_user_dir}}"

      - name: "Clone the Spring repository"
        git:
            repo: "https://github.com/JohnSkouloudis/BloodDonorApp-Backend"
            dest: "{{ appdir }}"
            version: "{{ branch }}"
            force: yes

      - name: "Populate application.properties"
        lineinfile:
          dest: "{{ appdir }}/src/main/resources/application.properties"
          state: present
          regexp: "^{{item.key}}="
          line: "{{item.key}}={{item.value}}"
        with_items:
          - "{{app.env | dict2items}}"

      - name: "Ensure mvnw is executable"
        file:
          path: "{{ appdir }}/mvnw"
          mode: '0755'
          state: file

      - name: "Build the Spring application"
        command: "./mvnw package -Dmaven.test.skip "
        args:
            chdir: "{{ appdir }}"
        become: yes

      - name: "Copy spring service file"
        template:
          src: ../files/spring.service.j2
          dest: "/etc/systemd/system/spring.service"
        become: yes
        become_user: root
        notify: restart spring

      - name: "Reload spring service"
        service:
          name: spring
          state: restarted
        become: yes

      - name: "Ensure spring service started"
        service:
          name: spring
          state: started
          enabled: yes
        become: yes


  handlers:
  - name: restart spring
    service:
      name: spring
      state: restarted
    become: yes

