---
- hosts: all
  become: yes
  tasks:

    - name: Check if Docker and Docker Compose v2 are installed
      shell: docker --version && docker-compose version
      register: docker_version_result
      ignore_errors: true

    - name: Set Docker installed fact
      set_fact:
        docker_installed: "{{ docker_version_result.rc == 0 }}"

    - name: Include install_docker playbook if Docker is not installed
      include_tasks: import_docker_playbook.yml
      when: not docker_installed

    - name: Clone the Spring repository
      git:
        repo: "https://github.com/JohnSkouloudis/BloodDonorApp-Backend"
        dest: "{{ backappdir }}"
        version: "{{ backbranch }}"
        force: yes

    - name: Populate application.properties
      lineinfile:
        dest: "{{ backappdir }}/src/main/resources/application.properties"
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}={{item.value}}"
      with_items:
        - "{{backapp.env | dict2items}}"

    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: "{{ backappdir }}"
        state: absent
        

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ backappdir }}"
        build: always
        state: present
      register: output
      notify: Restart Docker Compose

  handlers:
    - name: Restart Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ backappdir }}"
        state: restarted
