---
- hosts: frontendservers

  pre_tasks:

    - name: Update the apt package index
      apt:
        update_cache: yes
      become: yes

    - name: "Find my public ip"
      uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    - name: "See public ip"
      debug:
        var: ip_response.content

    - name: "Install Nginx"
      package:
        name: nginx
        state: latest
      become: yes

    - name: "Install nvm"
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: "Setup .profile"
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

    - name: "Debug"
      ansible.builtin.debug:
        msg: "PATH : {{ ansible_env.PATH }}"

    - name: "Install node"
      shell: |
        source $HOME/.nvm/nvm.sh && nvm install 20.12.1
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v20.12.1"


    - name: "Install Git"
      package:
        name: git
        state: latest
      become: yes

  tasks:
    - name: "Clone the Vue repository"
      git:
          repo: "https://github.com/PanayiotisPerdios/blood-donor-app-frontend"
          dest: "{{ frontappdir }}"
          version: "{{ frontbranch }}"
          force: yes

    - name: "Copy env file"
      shell : "cp {{frontappdir}}/.env {{frontappdir}}/.env.example"
  

    - name: "Populate .env"
      lineinfile:
          dest: "{{ frontappdir }}/.env"
          state: present
          regexp: "^{{item.key}}="
          line: "{{item.key}}={{item.value}}"
      with_items:
          - "{{frontapp.env | dict2items}}"

    - name: Install npm dependencies
      shell: |
        export NVM_DIR="$HOME/.nvm"
        source $NVM_DIR/nvm.sh
        nvm use default
        npm install
      args:
        chdir: "{{ frontappdir }}"
        executable: /bin/bash

    - name: Build the Vue.js application
      shell: |
        export NVM_DIR="$HOME/.nvm"
        source $NVM_DIR/nvm.sh
        nvm use default
        npm run build
      args:
        chdir: "{{ frontappdir }}"
        executable: /bin/bash



    - name: "Copy dist in nginx location"
      copy:
        src: "{{ frontappdir }}/dist/"
        dest: "{{ frontsite_location }}"
        remote_src: True
        mode: 7777
        force: true
      notify: restart nginx
      become: yes

    - name: copy nginx conf file
      template:
        src: ../files/nginx.vue.j2
        dest: "/etc/nginx/sites-available/vue"
      become: yes

    - name: enable vue site in nginx
      file:
        src: "/etc/nginx/sites-available/vue"
        dest: "/etc/nginx/sites-enabled/vue"
        state: link
      become: yes

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
      notify: restart nginx


  handlers:

    - name: restart vuejs
      service:
        name: vuejs
        state: restarted
      become: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
